kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-deploy-rb
  namespace: turniere-frontend
subjects:
  - kind: ServiceAccount
    name: gitlab-deploy
    namespace: gitlab
roleRef:
  kind: ClusterRole
  name: gitlab-deploy-role
  apiGroup: rbac.authorization.k8s.io
