apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: turniere-frontend
spec:
  selector:
    app: turniere-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress-http
  namespace: turniere-frontend
spec:
  entryPoints:
    - http
  routes:
    - match: Host(`frontend01.turnie.re`) || Host(`turnie.re`)
      kind: Rule
      services:
        - name: frontend-service
          port: 80
      middlewares:
        - name: redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frontend-ingress-https
  namespace: turniere-frontend
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`frontend01.turnie.re`) || Host(`turnie.re`)
      kind: Rule
      services:
        - name: frontend-service
          port: 80
  tls:
    certResolver: default
